import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pedido de namoro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* Player de áudio global, toca em todas as páginas */}
        <audio controls autoPlay loop style={{ position: "fixed", bottom: 16, left: 16, zIndex: 9999 }}>
          <source src="/music/Jorge & Mateus - Ai Já Era - [Novo DVD Live in London] - (Clipe Oficial).mp3" type="audio/mpeg" />
          Seu navegador não suporta áudio.
        </audio>
        {children}
      </body>
    </html>
  );
}


